# Generated by Django 3.0.8 on 2020-09-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('picture1', models.ImageField(upload_to='categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxapp.categoria')),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
            },
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=256)),
                ('description2', models.CharField(max_length=4096)),
                ('picture1', models.ImageField(upload_to='productos')),
                ('picture2', models.ImageField(upload_to='productos')),
                ('picture3', models.ImageField(upload_to='productos')),
                ('points', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxapp.categoria')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxapp.subcategoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
